#!/usr/bin/env python -u

import sys
import socket
import threading
import time
import random



def send_data(local_host_name, dest):
	dest_ip = dest.split(':')[0]
	dest_port = int(dest.split(':')[1])
	success_rate = 1 - lost_rate
	while True:
		random_num = random.random()
		if random_num < success_rate:
			sock.sendto(local_host_name, (dest_ip, dest_port))
			data, addr = sock.recvfrom(1024)
                        print data
		time.sleep(10)


def main():
	global lost_rate
	lost_rate = 0.1
	recv_port = 7999x
	
	arguments = sys.argv


	if (len(arguments) < 6 or arguments[1] != '-l' or arguments[3] != '-p'):
		print "usage: Jrip -l <lost_rate> -p <receive_port> <destination_host1> ..."
		sys.exit(1)

	local_host_name = 'local_host'
	lost_rate = float(arguments[2])
	recv_port = int(arguments[4])
	hosts = arguments[5:]
	t = range(len(hosts))
	
	
	
	#recv data
	global sock 
	sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
	sock.bind(('', recv_port))

	for i in range(len(hosts)):
		t[i] = threading.Thread(target = send_data, args = (local_host_name, hosts[i], ))
		t[i].start()

	


if __name__ == '__main__':
    main()



 



